#!/work/_builds/linux-x64/scy/python3/yosyshq/py3bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from scy.scy import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
